/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.skripsi.majid.view.dialog;

import com.skripsi.majid.db.DBConnection;
import com.skripsi.majid.entity.Pemilik;
import com.skripsi.majid.service.PemilikService;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author majid
 */
public class PemilikDialog extends javax.swing.JDialog {

    private Pemilik pemilik;
    private List<Pemilik> pemilikRecords = new ArrayList<Pemilik>();

    /**
     * Creates new form PemilikDialog
     */
    public PemilikDialog() {
        setModal(true);
        initComponents();
        loadRecords();

        jTablePemilik.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (jTablePemilik.getSelectedRow() != -1) {
                    int index = jTablePemilik.getSelectedRow();
                    String nama = (String) jTablePemilik.getValueAt(index, 1);
                    String alamat = (String) jTablePemilik.getValueAt(index, 2);
                    String telepon = (String) jTablePemilik.getValueAt(index, 4);

                    jTextFieldNama.setText(nama);
                    jTextAreaAlamat.setText(alamat);
                    jTextFieldTelepon.setText(telepon);

                }
            }
        });

    }

    public void muncul() {
        setTitle("Pemilik");
        setLocationRelativeTo(this);
        setVisible(true);
    }

    public void loadRecords() {
        try {
            DBConnection conn = DBConnection.getInstance();
            PemilikService service = new PemilikService(conn.getCon());
            pemilikRecords = service.getAll();
            setClearTextField();
            this.setFillTable();
        } catch (SQLException ex) {
            Logger.getLogger(PemilikService.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
// method untuk mengosongkan table
//    private void setClearTable() {
//        jTablePemilik.setModel(new javax.swing.table.DefaultTableModel(
//                new Object[][]{
//                    {null, null, null, null, null}
//                },
//                new String[]{
//                    "Id", "Nama", "Alamat", "Tanggal", "Telepon"
//                }));
//    }

    private void setFillTable() {
        Object data[][] = new Object[pemilikRecords.size()][6];
        int x = 0;
        for (Pemilik pemilik : pemilikRecords) {
            data[x][0] = pemilik.getId();
            data[x][1] = pemilik.getNamaPemilik();
            data[x][2] = pemilik.getAlamat();
            data[x][3] = pemilik.getTanggal();
            data[x][4] = pemilik.getTelepon();
            ++x;
        }
        String[] judul = {"Id", "Nama", "Alamat", "Tanggal", "Telepon"};
        jTablePemilik.setModel(new DefaultTableModel(data, judul));
        jScrollPane2.setViewportView(jTablePemilik);
    }

    private void setClearTextField() {
        jTextFieldNama.setText("");
        jTextAreaAlamat.setText("");
        jTextFieldTelepon.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAlamat = new javax.swing.JTextArea();
        jXDatePickerTanggal = new org.jdesktop.swingx.JXDatePicker();
        jTextFieldTelepon = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePemilik = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonTambah = new javax.swing.JButton();
        jButtonKembali = new javax.swing.JButton();
        jButtonUbah = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Pemilik"));

        jLabel2.setText("Nama :");

        jLabel3.setText("Alamat :");

        jLabel4.setText("Tanggal :");

        jLabel5.setText("Telepon :");

        jTextAreaAlamat.setColumns(20);
        jTextAreaAlamat.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAlamat);

        jXDatePickerTanggal.setDate(new Date());

        jScrollPane2.setViewportView(jTablePemilik);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(jTextFieldNama)
                    .addComponent(jXDatePickerTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldTelepon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jXDatePickerTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );

        jButtonTambah.setText("Tambah");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });

        jButtonKembali.setText("Kembali");
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });

        jButtonUbah.setText("Ubah");
        jButtonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbahActionPerformed(evt);
            }
        });

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pemilik");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skripsi/majid/resource/searchbutton.png"))); // NOI18N

        jTextFieldSearch.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButtonTambah)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonUbah)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonHapus)
                        .addGap(65, 65, 65)
                        .addComponent(jButtonKembali)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTambah)
                    .addComponent(jButtonKembali)
                    .addComponent(jButtonUbah)
                    .addComponent(jButtonHapus))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        if (jTextFieldNama.getText().trim().isEmpty() || jTextAreaAlamat.getText().trim().isEmpty() || jTextFieldTelepon.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap diisi semua field");
        } else {
            pemilik = new Pemilik();
            pemilik.setNamaPemilik(jTextFieldNama.getText());
            pemilik.setAlamat(jTextAreaAlamat.getText());
            pemilik.setTanggal(new Date());
            pemilik.setTelepon(jTextFieldTelepon.getText());

            try {
                DBConnection conn = DBConnection.getInstance();
                PemilikService service = new PemilikService(conn.getCon());
                service.insert(pemilik);
                JOptionPane.showMessageDialog(this, "Data Saved!");
                loadRecords();
            } catch (SQLException ex) {
                Logger.getLogger(PemilikDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbahActionPerformed
        if (jTablePemilik.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih salah satu baris");
        } else {
            int index = jTablePemilik.getSelectedRow();
            int id = (int) jTablePemilik.getValueAt(index, 0);

            Pemilik pemilik = new Pemilik();
            pemilik.setId(id);
            pemilik.setNamaPemilik(jTextFieldNama.getText());
            pemilik.setTanggal(jXDatePickerTanggal.getDate());
            pemilik.setAlamat(jTextAreaAlamat.getText());
            pemilik.setTelepon(jTextFieldTelepon.getText());

            try {
                DBConnection conn = DBConnection.getInstance();
                PemilikService service = new PemilikService(conn.getCon());
                service.update(pemilik);
                JOptionPane.showMessageDialog(this, "Data Telah Diubah!");
                loadRecords();
            } catch (SQLException ex) {
                Logger.getLogger(PemilikDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonUbahActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        if (jTablePemilik.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih salah satu baris");
        } else {
            int hasil = JOptionPane.showConfirmDialog(this, "Apakah anda yakin akan menghapus data ini?");
            if (hasil == JOptionPane.OK_OPTION) {
                int index = jTablePemilik.getSelectedRow();
                int id = (int) jTablePemilik.getValueAt(index, 0);

                try {
                    DBConnection conn = DBConnection.getInstance();
                    PemilikService service = new PemilikService(conn.getCon());
                    service.delete(id);
                    JOptionPane.showMessageDialog(this, "Data Telah Dihapus!");
                    loadRecords();
                } catch (SQLException ex) {
                    Logger.getLogger(PemilikDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }


        }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void Search(JTable jt, String keyword) {
        TableModel tm = jt.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tm);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)"+keyword));
        jt.setRowSorter(sorter);
     }
    
    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        try {
            Search(jTablePemilik, jTextFieldSearch.getText());
        } catch (PatternSyntaxException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jTextFieldSearchActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JButton jButtonUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTablePemilik;
    private javax.swing.JTextArea jTextAreaAlamat;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldTelepon;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerTanggal;
    // End of variables declaration//GEN-END:variables
}
