/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.skripsi.majid.view.dialog;

import com.skripsi.majid.db.DBConnection;
import com.skripsi.majid.entity.Pemilik;
import com.skripsi.majid.entity.Sapi;
import com.skripsi.majid.entity.SapiTerpilih;
import com.skripsi.majid.service.PemilikService;
import com.skripsi.majid.service.SapiService;
import com.skripsi.majid.service.TableAwalService;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.apache.velocity.runtime.directive.Break;

/**
 *
 * @author majid
 */
public class SapiDialog extends javax.swing.JDialog {

    /**
     * Creates new form PemilikDialog
     */
    float angka;
    int sehat = 0;
    int cedera = 0;
    private List<Sapi> sapiRecords = new ArrayList<Sapi>();
    DBConnection conn = DBConnection.getInstance();

    public SapiDialog() {
        setModal(true);
        initComponents();

        loadRecords();
        loadPemilik();
        autoNumber();
    }

    public void muncul() {
        setTitle("Sapi");
        setLocationRelativeTo(this);
        setVisible(true);
    }

    public void loadRecords() {
        try {
            SapiService service = new SapiService(conn.getCon());
            sapiRecords = service.getAll();
            this.setFillTable();
        } catch (SQLException ex) {
            Logger.getLogger(SapiDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setFillTable() {
        Object data[][] = new Object[sapiRecords.size()][8];
        int x = 0;
        for (Sapi sapi : sapiRecords) {
            data[x][0] = sapi.getId();
            data[x][1] = sapi.getPemilik().getId();
            data[x][2] = sapi.getUmur();
            data[x][3] = sapi.getBerat();
            data[x][4] = sapi.getKesehatan();
            data[x][5] = sapi.getJk();
            data[x][6] = sapi.getHarga();
            ++x;
        }
        String[] judul = {"Id Sapi", "Pemilik Id", "Umur", "Berat", "Kesehatan", "Jenis Kelamin", "Harga"};
        jTableSapi.setModel(new DefaultTableModel(data, judul));
        jScrollPane1.setViewportView(jTableSapi);
    }

    private void loadPemilik() {
        try {
            PemilikService service = new PemilikService(conn.getCon());
            List<Pemilik> list = service.getAll();

            for (Pemilik pemilik : list) {
                jComboBoxKetPemilik.addItem(pemilik);
            }
        } catch (SQLException ex) {
            Logger.getLogger(SapiDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void autoNumber() {
        try {
            SapiService service = new SapiService(conn.getCon());
            String number = service.getAutoNumber();
            jTextFieldIdsapi.setText(number);
        } catch (SQLException ex) {
            Logger.getLogger(SapiDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void resetAll() {
        jComboBoxKetPemilik.removeAllItems();
        loadPemilik();
        jFormattedTextFieldBerat.setValue(new Long(0));
        //    jComboBoxKesehatan.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"----- Pilih Kesehatan -----", "Sehat", "Luka/Cedera/Patah Tulang", "Sakit"}));
        jComboBoxJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"----- Pilih Jenis Kelamin -----", "jantan", "betina"}));
        jComboBoxUmur.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"----- Pilih Umur -----", "< 1.5 Tahun", "1.5 - <2 Tahun", "2 - <2.5 Tahun", "2.5 - <3 Tahun", "3 - <3.5 Tahun", "3.5 - <4 Tahun", "> 4 Tahun"}));

        jCheckBox1.setSelected(true);
        jCheckBox2.setSelected(true);
        jCheckBox3.setSelected(true);
        jCheckBox4.setSelected(true);
        jCheckBox5.setSelected(true);
        jCheckBox6.setSelected(true);
        jCheckBox7.setSelected(true);
        jCheckBox8.setSelected(true);
        jCheckBox9.setSelected(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIdsapi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxKetPemilik = new javax.swing.JComboBox();
        jComboBoxUmur = new javax.swing.JComboBox();
        jFormattedTextFieldBerat = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxJenisKelamin = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSapi = new javax.swing.JTable();
        jButtonPilih = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonKembali = new javax.swing.JButton();
        jButtonSimpan = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Sapi"));

        jLabel2.setText("No/Id Sapi");

        jTextFieldIdsapi.setEditable(false);

        jLabel3.setText("Berat");

        jLabel4.setText("Umur");

        jLabel5.setText("Kesehatan");

        jLabel6.setText("Jenis Kelamin");

        jLabel7.setText("Keterangan Pemilik");

        jComboBoxUmur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----- Pilih Umur -----", "< 1.5 Tahun", "1.5 - <2 Tahun", "2 - <2.5 Tahun", "2.5 - <3 Tahun", "3 - <3.5 Tahun", "3.5 - <4 Tahun", ">= 4 Tahun" }));

        jFormattedTextFieldBerat.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldBerat.setValue(new Long(0));

        jLabel8.setText("Kg");

        jComboBoxJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----- Pilih Jenis Kelamin -----", "jantan", "betina" }));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jScrollPane1.setViewportView(jTableSapi);

        jButtonPilih.setText("Pilih Sapi");
        jButtonPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPilihActionPerformed(evt);
            }
        });

        jButtonNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skripsi/majid/resource/nextbutton.png"))); // NOI18N
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Tubuh normal");

        jCheckBox2.setText("Lubang kumla tidak keluar cairan");

        jCheckBox3.setText("Kaki Simetris");

        jCheckBox4.setText("Sikap & tingkah laku normal");

        jCheckBox5.setText("Nafsu makan normal");

        jCheckBox6.setText("Pernafasan stabil");

        jCheckBox7.setText("Pembuangan kotoran lancar");

        jCheckBox8.setText("Mata cerah");

        jCheckBox9.setText("Anggota tubuh lengkap & tidak cedera/luka");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox8)
                            .addComponent(jCheckBox9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFormattedTextFieldBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addComponent(jComboBoxKetPemilik, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIdsapi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonPilih)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonPilih, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonNext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldIdsapi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxKetPemilik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextFieldBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jCheckBox1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox9)
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jComboBoxJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47))))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Sapi");

        jTextFieldSearch.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skripsi/majid/resource/searchbutton.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButtonKembali.setText("Kembali");
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButtonSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReset)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonKembali)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonHapus)
                        .addComponent(jButtonReset)
                        .addComponent(jButtonSimpan))
                    .addComponent(jButtonKembali))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        Long berat = (Long) jFormattedTextFieldBerat.getValue();
        Pemilik pemilik = (Pemilik) jComboBoxKetPemilik.getSelectedItem();
        
        if (jTextFieldIdsapi.getText().trim().isEmpty() || jComboBoxUmur.getSelectedIndex() == 0
                || berat == 0 || jComboBoxJenisKelamin.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Pengisian salah,Harap diisi dengan benar!!!!");
        } else {
            try {
                Sapi sapi = new Sapi();
                sapi.setId(Integer.valueOf(jTextFieldIdsapi.getText()));
                sapi.setPemilik(pemilik);
                //////////////////////////////////////////////////////////
                if (jComboBoxUmur.getSelectedIndex() == 1) {
                    sapi.setUmur("<1.5tahun");
                } else if (jComboBoxUmur.getSelectedIndex() == 2) {
                    sapi.setUmur("1.5-<2tahun");
                } else if (jComboBoxUmur.getSelectedIndex() == 3) {
                    sapi.setUmur("2-<2.5tahun");
                } else if (jComboBoxUmur.getSelectedIndex() == 4) {
                    sapi.setUmur("2.5-<3tahun");
                } else if (jComboBoxUmur.getSelectedIndex() == 5) {
                    sapi.setUmur("3-<3.5tahun");
                } else if (jComboBoxUmur.getSelectedIndex() == 6) {
                    sapi.setUmur("3.5-<4tahun");
                } else if (jComboBoxUmur.getSelectedIndex() == 7) {
                    sapi.setUmur(">=4tahun");
                }
                //////////////////////////////////////////////////////////
                sapi.setBerat(berat);

                //////////////////////////////////////////////////////////
                if (jComboBoxJenisKelamin.getSelectedIndex() == 1) {
                    sapi.setJk("jantan");
                } else if (jComboBoxJenisKelamin.getSelectedIndex() == 2) {
                    sapi.setJk("betina");
                }
                ///////////////////////////////////////////////////////// 
                if (jCheckBox1.isSelected()) {
                    sehat = sehat + 1;
                }
                if (jCheckBox2.isSelected()) {
                    sehat = sehat + 1;
                }
                if (jCheckBox3.isSelected()) {
                    sehat = sehat + 1;
                }
                if (jCheckBox4.isSelected()) {
                    sehat = sehat + 1;
                }
                if (jCheckBox5.isSelected()) {
                    sehat = sehat + 1;
                }
                if (jCheckBox6.isSelected()) {
                    sehat = sehat + 1;
                }
                if (jCheckBox7.isSelected()) {
                    sehat = sehat + 1;
                }
                if (jCheckBox8.isSelected()) {
                    sehat = sehat + 1;
                }
                if (jCheckBox9.isSelected()) {
                    cedera = cedera + 1;
                }
                System.out.println(sehat);
                System.out.println(cedera);
////////////////////////////////////////////////////////////////////////////////
                if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected()
                        && jCheckBox4.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected()
                        && jCheckBox7.isSelected() && jCheckBox8.isSelected() && jCheckBox9.isSelected()) {
                    sapi.setKesehatan("sehat");
                } else if (jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected()
                        && jCheckBox4.isSelected() && jCheckBox5.isSelected() && jCheckBox6.isSelected()
                        && jCheckBox7.isSelected() && jCheckBox8.isSelected()) {
                    sapi.setKesehatan("sehat-cedera");
                } else if ((sehat == 0 || sehat == 1 || sehat == 2 || sehat == 3 || sehat == 4 || sehat == 5 || sehat == 6 || sehat == 7) && cedera == 1) {
                    sapi.setKesehatan("sakit");
                } else if ((sehat == 0 || sehat == 1 || sehat == 2 || sehat == 3 || sehat == 4 || sehat == 5 || sehat == 6 || sehat == 7) && cedera == 0) {
                    sapi.setKesehatan("sakit-cedera");
                }
                /////////////////////////////////////////////////////////
                TableAwalService serviceTableAwal = new TableAwalService(conn.getCon());
                float hargaperkg = (float) serviceTableAwal.getHarga();
                sapi.setHarga(berat*hargaperkg);
                /////////////////////////////////////////////////////////


                SapiService service = new SapiService(conn.getCon());
                service.insert(sapi);
                JOptionPane.showMessageDialog(this, "Data Saved!");
                loadRecords();
                resetAll();
                sehat = 0;
                cedera = 0;
                autoNumber();
            } catch (SQLException ex) {
                Logger.getLogger(SapiDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed
    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        resetAll();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        if (jTableSapi.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih salah satu baris");
        } else {
            int hasil = JOptionPane.showConfirmDialog(this, "Apakah anda yakin akan menghapus data ini?");
            if (hasil == JOptionPane.OK_OPTION) {
                int index = jTableSapi.getSelectedRow();
                int id = (int) jTableSapi.getValueAt(index, 0);

                try {
                    SapiService service = new SapiService(conn.getCon());
                    service.delete(id);
                    JOptionPane.showMessageDialog(this, "Data Telah Dihapus!");
                    loadRecords();


                } catch (SQLException ex) {
                    Logger.getLogger(PemilikDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        autoNumber();
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        try {
            Search(jTableSapi, jTextFieldSearch.getText());
        } catch (PatternSyntaxException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jButtonPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPilihActionPerformed
        try {
            conn.getCon().setAutoCommit(false);
            SapiTerpilih st = new SapiTerpilih();
            int index = jTableSapi.getSelectedRow();

            SapiService service = new SapiService(conn.getCon());
            int dataIdSapi = service.cekData(index);
            int maxSapiTerpilih = service.getMaxSapiTerpilih();

            if (jTableSapi.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih salah satu baris dari sapi yang mau diseleksi dan Isi budget yg dimiliki");
            } else if (index + 1 == dataIdSapi) {
                JOptionPane.showMessageDialog(this, "Sapi tersebut sudah terpilih");
            } else if (maxSapiTerpilih > 3) {
                int pilihan = JOptionPane.showOptionDialog(this, "Maaf data sapi yang terpilih max 4!!!!, Kosongkan data", "Kosongkan data", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, new String[]{"ya", "tidak"}, "ya");
                if (pilihan == 0) {
                    service.kosongkan();
                }
            } else {
                int idSapi = (int) jTableSapi.getValueAt(index, 0);
                String umur = (String) jTableSapi.getValueAt(index, 2);
                float berat = (float) jTableSapi.getValueAt(index, 3);
                String kesehatan = (String) jTableSapi.getValueAt(index, 4);
                String jk = (String) jTableSapi.getValueAt(index, 5);


                st.setSapiid(idSapi);
                //////////////////////////////////////////////////////////
                if (umur.equals("<1.5tahun")) {
                    st.setUmur(1);
                    System.out.println("umur <1.5 tahun => nilai umur 1");
                } else if (umur.equals("1.5-<2tahun")) {
                    st.setUmur(2);
                    System.out.println("umur 1.5 tahun - < 2 tahun => nilai umur 2");
                } else if (umur.equals("2-<2.5tahun")) {
                    st.setUmur(3);
                    System.out.println("umur 2 tahun - < 2.5 tahun => nilai umur 3");
                } else if (umur.equals("2.5-<3tahun")) {
                    st.setUmur(4);
                    System.out.println("umur 2.5 tahun - < 3 tahun => nilai umur 4");
                } else if (umur.equals("3-<3.5tahun")) {
                    st.setUmur(5);
                    System.out.println("umur 3 tahun - < 3.5 tahun => nilai umur 5");
                } else if (umur.equals("3.5-<4tahun")) {
                    st.setUmur(6);
                    System.out.println("umur 3.5 tahun - < 4 tahun => nilai umur 6");
                } else if (umur.equals(">=4tahun")) {
                    st.setUmur(7);
                    System.out.println("umur >= 4 tahun => nilai umur 7");
                }
                //////////////////////////////////////////////////////////
                if (berat <= 150) {
                    st.setBerat(0.5F);
                } else if (berat > 150 && berat <= 165) {
                    st.setBerat(1F);
                } else if (berat > 165 && berat <= 180) {
                    st.setBerat(1.5F);
                } else if (berat > 180 && berat <= 195) {
                    st.setBerat(2F);
                } else if (berat > 195 && berat <= 210) {
                    st.setBerat(2.5F);
                } else if (berat > 210 && berat <= 225) {
                    st.setBerat(3F);
                } else if (berat > 225 && berat <= 240) {
                    st.setBerat(3.5F);
                } else if (berat > 240 && berat <= 255) {
                    st.setBerat(4F);
                } else if (berat > 255 && berat <= 270) {
                    st.setBerat(4.5F);
                } else if (berat > 270 && berat <= 285) {
                    st.setBerat(5F);
                } else if (berat > 285 && berat <= 300) {
                    st.setBerat(5.5F);
                } else if (berat > 300 && berat <= 315) {
                    st.setBerat(6F);
                } else if (berat > 315 && berat <= 330) {
                    st.setBerat(6.5F);
                } else if (berat > 330 && berat <= 345) {
                    st.setBerat(7F);
                } else if (berat > 345 && berat <= 360) {
                    st.setBerat(7.5F);
                } else if (berat > 360 && berat <= 375) {
                    st.setBerat(8F);
                } else if (berat > 375 && berat <= 390) {
                    st.setBerat(8.5F);
                } else if (berat > 390) {
                    st.setBerat(9F);
                }
                //////////////////////////////////////////////////////////
                if (kesehatan.equals("sehat")) {
                    st.setKesehatan(9);
                    System.out.println("sehat => nilai kesehatan 9");
                } else if (kesehatan.equals("sehat-cedera")) {
                    st.setKesehatan(7);
                    System.out.println("sehat-cedera => nilai kesehatan 7");
                } else if (kesehatan.equals("sakit")) {
                    st.setKesehatan(3);
                    System.out.println("sakit => nilai kesehatan 3");
                } else if (kesehatan.equals("sakit-cedera")) {
                    st.setKesehatan(1);
                    System.out.println("sakit-cedera => nilai kesehatan 1");
                }

                //////////////////////////////////////////////////////////
                if (jk.equals("jantan")) {
                    st.setJk(2);
                    System.out.println("jantan => nilai jk 2");
                } else if (jk.equals("betina")) {
                    st.setJk(1);
                    System.out.println("betina => nilai jk 1");
                }

                service.insertSapiTerpilih(st);
                conn.getCon().commit();
                conn.getCon().setAutoCommit(true);
                JOptionPane.showMessageDialog(this, "Sapi " + idSapi + " saved");
            }
        } catch (SQLException ex) {
            try {
                conn.getCon().rollback();
                conn.getCon().setAutoCommit(true);


            } catch (SQLException ex1) {
                Logger.getLogger(SapiDialog.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }//GEN-LAST:event_jButtonPilihActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        dispose();
        TableAwalDialog dialog = new TableAwalDialog();
        dialog.muncul();
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void Search(JTable jt, String keyword) {
        TableModel tm = jt.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tm);
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + keyword));
        jt.setRowSorter(sorter);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPilih;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox jComboBoxJenisKelamin;
    private javax.swing.JComboBox jComboBoxKetPemilik;
    private javax.swing.JComboBox jComboBoxUmur;
    private javax.swing.JFormattedTextField jFormattedTextFieldBerat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableSapi;
    private javax.swing.JTextField jTextFieldIdsapi;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
